### ISSUE TITLE
activateTabFromUrl doesn't work well with syncTabsWithSameLabels

### ISSUE THREAD

**Issue by 4rnoP** [Ovski4/jekyll-tabs#15]
Hi,

I encountered an issue when trying to use both activateTabFromUrl and syncTabsWithSameLabels.
Indeed, on page load, only the first tabs section is set to the correct tab content, the following tabs section with identical areas are still set to the first item.
I resolved the issue locally by adding a call to `syncTabsWithSameLabels(tabLink)` to the end of the `activateTabFromUrl` function, but it might need some more tinkering as, in the situation where syncTabsWithSameLabels is disable and activateTabFromUrl is enabled, should it only set the first tabs section ?

Also, I noticed that in `lib/template.erb`, the id of the tabs section is set to the label of the tabs section, which can result in multiple elements having the same id (by using syncTabsWithSameLabels for example). This technically violates the HTML specs.

Great and useful plugin anyway, it's really easy to use.

**Comment by Ovski4** [comment]
Hi :wave:

By any chance, would you happen to have multiple groups of tabs with the same name?

Taking this from the docs to clarify what I mean by group of tabs:

> In the following markup:
> {% tab data-struct Some label here %}
> The first word after the tab keyword (data-struct here) is used to group tabs.

- The id of the list of tabs  (\<ul> element) is set to the name of the group of tab
- The id of the tab items (\<li> element) is set to the name of the group of tab + the label

So it is important that you don't have multiple group of tabs with the same name. As you found out, if you do you'll end up with groups of tabs having the same id and that will cause bugs when both `activateTabFromUrl` and `syncTabsWithSameLabels` are enabled.

If this is not the problem here, can you share a simplified version of all your group tabs? I could look into reproducing the issue to find a fix
