### ISSUE TITLE
Copy code

### ISSUE THREAD

**Issue by jmount1992** [Ovski4/jekyll-tabs#8]
Another great feature to add to the plugin would be a copy code feature in-built.

**Comment by Ovski4** [comment]
That's a good idea 🤔 

I'm not sure if I should start accepting all requests since people are free to fork this project, but it's not so bad as long as it's configured and people can turn on / or off the features as they want.

Like mentioned in the previous issue, I pushed some changes to the [tabs.js](https://github.com/Ovski4/jekyll-tabs/blob/master/docs/tabs.js) file that will allow you to do that. This behavior will be turned off by default.

You can:

- Update the content in your javascript file with the latest version
- Follow instructions [here](https://github.com/Ovski4/jekyll-tabs#add-a-copy-to-clipboard-button)

Let me know if that works for you 🙂

**Comment by jmount1992** [comment]
Also worked perfectly and easy to implement!
